baseURL = 'https://wahidkadwaikar.github.io'
languageCode = 'en-us'
title = 'Letters from L1'
theme = 'archie'

[params]
  mode = "toggle"
  useCDN = false
  subtitle = "-rwxr-xr-x`"
  mathjax = true
  katex = true

# Social Tags
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/wahidkadwaikar"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
